spring:
  application:
    name: blog-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/blogdb   # use service name from docker-compose
    username: postgres
    password: postgres   # uses env var or fallback
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update     # use Flyway/Liquibase for schema updates
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8081

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
